version: '3'

volumes:
  data:
  config:

services:
  grafana:
    image: grafana/grafana:4.6.2
    container_name: grafana
    environment:
      - "GF_SECURITY_ADMIN_PASSWORD=password"
    volumes:
      - data:/var/lib/grafana
      - config:/etc/grafana
    ports:
      - 3000:3000
    restart: always