version: '3'

volumes:
  snapshot:
  data:

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.1
    container_name: elasticsearch
    environment:
      - cluster.name=prokosna-es
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - discovery.zen.minimum_master_nodes=2
      - discovery.zen.ping.unicast.hosts=ranko.prokosna.internal,asuka.prokosna.internal
      - "ES_JAVA_OPTS=-Xms10g -Xmx10g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - data:/usr/share/elasticsearch/data
      - snapshot:/usr/share/elasticsearch/snapshot
    ports:
      - 9200:9200
      - 9300:9300
    restart: always